mode: interactive  # 'interactive', 'script'; can be overriden by CLI arg
log-level: info  # 'debug', 'info', 'error'

sources:
  sample:
    video: resources/SampleVideo_360x240_5mb.mp4
    srt: resources/SampleVideo.srt
    id: SampleVideo

output:
  filename: output.jpg

  imgur:
    enabled: true
    # See: https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139    
    client-id: XXX-PLACEHOLDER-XXX
